version: "2"

linters:
  enable:
    - bodyclose
    - errcheck
    - errorlint
    - gocritic
    - gosec
    - govet
    - ineffassign
    - misspell
    - noctx
    - revive
    - staticcheck
    - unused
    - wsl_v5

formatters:
  enable:
    - gofmt
    - goimports
